// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "TesteWWDC",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "TesteWWDC",
            targets: ["AppModule"],
            bundleIdentifier: "jyuurin.TesteWWDC",
            teamIdentifier: "5786D2SAT2",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .coffee),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
